"""initial migration

Revision ID: 852afaf9b440
Revises: 
Create Date: 2025-12-27 13:46:53.552463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '852afaf9b440'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('characteristics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laboratory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), server_default='local', nullable=False),
    sa.CheckConstraint("type in ('local', 'regional', 'national', 'international', 'global')"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), server_default='guest', nullable=False, comment='Roles within the system'),
    sa.Column('laboratory_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("role in ('guest', 'student', 'staff', 'moderator', 'administrator')"),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String(), dimensions=1), nullable=False),
    sa.Column('size', sa.Integer(), server_default='0', nullable=False, comment='Total size in bytes'),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Fields/attributes names, description, with corresponding data types'),
    sa.ForeignKeyConstraint(['id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image_link', sa.String(), nullable=True),
    sa.Column('approval_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('laboratory_id', sa.Integer(), nullable=False),
    sa.Column('equipment_type_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("status in ('active', 'malfunctioned', 'maintenance', 'retired')"),
    sa.ForeignKeyConstraint(['equipment_type_id'], ['equipment_type.id'], ),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presentation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), server_default='0', nullable=False, comment='Duration in seconds'),
    sa.Column('subtitles', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Subtitles/transcription in different languages and formats'),
    sa.Column('visibility', sa.String(), nullable=False),
    sa.CheckConstraint("visibility in ('private_internal', 'stakeholders_only', 'public_community')"),
    sa.ForeignKeyConstraint(['id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("status in ('active', 'completed')"),
    sa.CheckConstraint("type in ('research', 'commercial', 'community')"),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.ARRAY(sa.String(), dimensions=1), nullable=False),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responsibility_zone', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.CheckConstraint("status in ('draft', 'submitted', 'revision', 'approved')"),
    sa.ForeignKeyConstraint(['id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('laboratory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('software_repository',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('lines_amount', sa.Integer(), server_default='0', nullable=False, comment='Amount of source lines of code'),
    sa.ForeignKeyConstraint(['id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), server_default='requested', nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.CheckConstraint("status IN ('requested','approved','rejected','cancelled','completed')"),
    sa.ForeignKeyConstraint(['approver_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_link', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('affiliation', sa.String(), nullable=True),
    sa.Column('interest_areas', sa.ARRAY(sa.String(), dimensions=1), nullable=False),
    sa.Column('posts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('project_participant',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'account_id'),
    comment='Person can participate in multiple projects (account m2m project)'
    )
    op.create_table('project_partner',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'partner_id'),
    comment='Partners can participate in multiple projects (project m2m partner)'
    )
    op.create_table('project_resource',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'resource_id'),
    comment='Resources can be reused or shared between different projects (project m2m resource)'
    )
    op.create_table('booking_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issued_when', sa.DateTime(timezone=True), nullable=False),
    sa.Column('returned_when', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('returned_when > issued_when'),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_history')
    op.drop_table('project_resource')
    op.drop_table('project_partner')
    op.drop_table('project_participant')
    op.drop_table('profile')
    op.drop_table('booking')
    op.drop_table('software_repository')
    op.drop_table('room')
    op.drop_table('report')
    op.drop_table('publication')
    op.drop_table('project')
    op.drop_table('presentation')
    op.drop_table('equipment')
    op.drop_table('dataset')
    op.drop_table('account')
    op.drop_table('resource')
    op.drop_table('partner')
    op.drop_table('laboratory')
    op.drop_table('equipment_type')
    # ### end Alembic commands ###
