"""initial migration

Revision ID: 581acf69c022
Revises: 
Create Date: 2026-01-24 13:11:00.324252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '581acf69c022'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('characteristics', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='similar to SKU (e.g., brand, model, weight depending on the context)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laboratory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('LOCAL', 'REGIONAL', 'NATIONAL', 'INTERNATIONAL', 'GLOBAL', name='partnertype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('GUEST', 'STUDENT', 'STAFF', 'MODERATOR', 'ADMINISTRATOR', name='accountrole'), nullable=False, comment='Role within the system'),
    sa.Column('laboratory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String(), dimensions=1), nullable=False),
    sa.Column('size', sa.Integer(), server_default='0', nullable=False, comment='Total size in bytes'),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Fields/attributes names, description, with corresponding data types'),
    sa.ForeignKeyConstraint(['id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'MALFUNCTIONED', 'MAINTENANCE', 'RETIRED', name='equipmentstatus'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('media_link', sa.String(), nullable=True, comment='video, image, audio, or other mimetype'),
    sa.Column('approval_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('laboratory_id', sa.Integer(), nullable=False),
    sa.Column('equipment_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_type_id'], ['equipment_type.id'], ),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presentation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), server_default='0', nullable=False, comment='Duration in seconds'),
    sa.Column('subtitles', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Subtitles/transcription in different languages and formats'),
    sa.Column('visibility', sa.Enum('PRIVATE_INTERNAL', 'STAKEHOLDERS_ONLY', 'PUBLIC_COMMUNITY', name='presentationvisibility'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('RESEARCH', 'COMMERCIAL', 'COMMUNITY', name='projecttype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', name='projectstatus'), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.ARRAY(sa.String(), dimensions=1), nullable=False),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responsibility_zone', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'REVISION', 'APPROVED', name='reportstatus'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False, comment='name, number, id (like C1.1.111 or in other formats)'),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('laboratory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('software_repository',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('lines_amount', sa.Integer(), server_default='0', nullable=False, comment='Amount of source lines of code'),
    sa.ForeignKeyConstraint(['id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('start_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'APPROVED', 'REJECTED', 'CANCELLED', 'COMPLETED', name='bookingstatus'), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.CheckConstraint('end_ts > start_ts'),
    sa.ForeignKeyConstraint(['approver_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_link', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('affiliation', sa.String(), nullable=True),
    sa.Column('interest_areas', sa.ARRAY(sa.String(), dimensions=1), nullable=False),
    sa.Column('posts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('project_participant',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'account_id'),
    comment='Person can participate in multiple projects (account m2m project)'
    )
    op.create_table('project_partner',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'partner_id'),
    comment='Partners can participate in multiple projects (project m2m partner)'
    )
    op.create_table('project_resource',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'resource_id'),
    comment='Resources can be reused or shared between different projects (project m2m resource)'
    )
    op.create_table('booking_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_history')
    op.drop_table('project_resource')
    op.drop_table('project_partner')
    op.drop_table('project_participant')
    op.drop_table('profile')
    op.drop_table('booking')
    op.drop_table('software_repository')
    op.drop_table('room')
    op.drop_table('report')
    op.drop_table('publication')
    op.drop_table('project')
    op.drop_table('presentation')
    op.drop_table('equipment')
    op.drop_table('dataset')
    op.drop_table('account')
    op.drop_table('resource')
    op.drop_table('partner')
    op.drop_table('laboratory')
    op.drop_table('equipment_type')
    # ### end Alembic commands ###
